#
HOST,cloudflare-dns.com,Proxy
HOST,dns.google,Proxy
IP-CIDR,1.1.1.1/32,Proxy,no-resolve
IP-CIDR,8.8.8.8/32,Proxy,no-resolve
#
HOST,dns.alicdn.com,DIRECT
HOST,doh.pub,DIRECT
IP-CIDR, 223.5.5.5/32, DIRECT, no-resolve
IP-CIDR, 119.29.29.29/32, DIRECT, no-resolve