# > 一些比较容易忽视的分流
host, ad.12306.cn, direct
host, sdkapp.uve.weibo.com, direct
;host-keyword, github, proxy
;IP-CIDR,95.161.76.0/20, proxy

host, gg.caixin.com, direct
host-suffix, ucweb.com, direct
host-suffix, kuwo.cn, direct
host, ntb.lanjie100.com, reject
